
name: builder

on: pull_request

jobs:
  main:
    runs-on: ubuntu-20.04 #ubuntu-latest

    steps:
      - name: Checkout base repo
        uses: actions/checkout@v3

      - name: Build datalayer.provider app
        id: provider-amd64
        uses: boschrexroth/ctrlx-actions/build-snap@v1
        with: 
            architecture: amd64
            path-app-files: datalayer.provider.all-data

      - name: Rename snap file
        run: |
          mv ${{steps.provider-amd64.outputs.path-snap}} datalayer.provider.all-data/sdk-py-provider-alldata_amd64.snap
        shell: bash

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: 2.1.1
          files: datalayer.provider.all-data/sdk-py-provider-alldata_amd64.snap